sudo: required
services:
  - docker

before_install:
  - docker build -t recepdirek/docker_react -f Dockerfile.dev .

#script:
#  - docker run recepdirek/docker_react npm run test -- --coverage
script:
  - docker run -e CI=true recepdirek/docker_react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name:  mybucket
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"