sudo: required
services:
  - docker

before_install:
  - docker build -t recepdirek/docker_react -f Dockerfile.dev .

#script:
#  - docker run recepdirek/docker_react npm run test -- --coverage
script:
  - docker run -e CI=true recepdirek/docker_react npm run test